#!/usr/bin/env bash

usage()
{
    cat <<EOF
Usage: kea-config [OPTIONS]
Options:
     [--prefix]
     [--hgversion]
     [--version]
     [--libs]
     [--cflags]
     [--ldflags]
     [--includes]
     [--hdfincludes]
     [--hdfcflags]
     [--hdflibs]
EOF
    exit $1
}
if test $# -eq 0; then
  usage 1 1>&2
fi
while test $# -gt 0; do
case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
esac
case $1 in
    --prefix)
    echo -n "C:/msys64/usr/local "
     ;;
    --hgversion)
    echo -n "289 "
     ;;
	--version)
    echo -n "1.4.7 "
     ;;
    --cflags)
    echo -n "-IC:/msys64/usr/local/include "
      ;;
    --libs)
      echo -n "-LC:/msys64/usr/local/lib -lkea "
      ;;
    --ldflags)
      echo -n "C:/msys64/usr/local/lib "
      ;;
    --includes)
      echo -n "C:/msys64/usr/local/include "
      ;;
	--hdfincludes)
      echo -n "/usr/local/include "
      ;;
	--hdfcflags)
      echo -n "-I/usr/local/include "
      ;;
	--hdflibs)
      echo -n "-L/usr/local/lib -lhdf5 -lhdf5_hl -lhdf5_cpp "
      ;;
  esac
  shift
done
echo
